<?php
// $Id$

/**
 * Implementation of hook_help().
 */
function skinr_export_help($path, $arg) {

}

/**
 * Implementation of hook_schema_alter().
 * Makes the skinr table usable by ctools' export.inc.
 */
function skinr_export_schema_alter(&$schema) {
  $schema['skinr']['export'] = array(
    'key' => 'sid',
    'primary key' => array('theme', 'module', 'sid'),
    'identifier' => 'skins',
    'default hook' => 'default_skinr_skins',
    'api' => array(
      'owner' => 'skinr_export',
      'api' => 'skinr',
      'minimum_version' => 1,
      'current_version' => 1,
    ), 
  );
}

/**
* Implementation of hook_ctools_plugin_api().
*/
function skinr_export_ctools_plugin_api($owner, $api) {
  if ($owner == 'skinr_export' && $api == 'skinr_skins') {
    return array('version' => 1);
  }
}

/**
 * Load a single skins object.
 */
function skinr_export_skins_load($name) {
  //TODO: Come back to this. This function does nothing right now, also I might be passing the wrong object,
  // Is late and I'm confused btwn the skins_skins, skins, and default_skinr_skins lol
  ctools_include('export');
  $result = ctools_export_load_object('skinr_skins', 'names', array($name));
  if (isset($result[$name])) {
    return $result[$name];
  }
}