<?php
// $Id$

/**
 * Implementation of hook_help().
 */
function skinr_export_help($path, $arg) {

}

/**
 * Implementation of hook_schema_alter().
 * Makes the skinr table usable by ctools' export.inc.
 */
function skinr_export_schema_alter(&$schema) {
  $schema['skinr']['export'] = array(
    'key' => 'sid',
    'primary key' => array('theme', 'module', 'sid'),
    'identifier' => 'skins',
    'default hook' => 'default_skinr_skins',
    'api' => array(
      'owner' => 'skinr_export',
      'api' => 'skinr',
      'minimum_version' => 1,
      'current_version' => 1,
    ), 
  );
}

/**
* Implementation of hook_ctools_plugin_api().
*/
function skinr_export_ctools_plugin_api($owner, $api) {
  if ($owner == 'skinr_export' && $api == 'skinr_skins') {
    return array('version' => 1);
  }
}

/**
* Implementation of hook__ctools_plugin_directory().
*/
function skinr_export_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && $plugin == 'export_ui') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Load a single skins object.
 */
function skinr_export_skins_load($name) {
  ctools_include('export');
  $result = ctools_export_load_object('skinr', 'names', array('sid' => $name));
  if (isset($result[$name])) {
    return $result[$name];
  }
}

/**
 * Load all skins object.
 */
function skinr_export_skins_load_all() {
  ctools_include('export');
  $result = ctools_export_load_object('skinr');
  return $result;
}

/**
 * A helper function to only get the skinr object that haven't been overwritten
 */
function _skinr_export_skins_load_only_code() {
  static $code_only_skins;

  if (isset($code_only_skins)) {
    return $code_only_skins;
  }
  
  $skins = skinr_export_skins_load_all();
  foreach ($skins as $sid) {
   if (isset($sid->export_type)) {
     $code_only_skins[$sid->sid] = $sid;
   }
  }
  
  return $code_only_skins;
}

/**
 * Implementation of hook_skinr_alter().
 */
function skinr_export_skinr_skins_alter(&$skins, $module, $sids, $settings) {
 static $exported_skins;

 if (!isset($exported_skins)) {
  //We only inject the exported skins into the skinr object if it live only in code 
  $exported_skins = _skinr_export_skins_load_only_code();
 }
 foreach ($sids as $sid) {
  if (isset($exported_skins[$sid])) {
    if ($exported_skins[$sid]->disabled) {
      //if the skin is disabled we're going to reset the skin array
      $_skinr = $skins['_skinr'];
      $_skinr_id = $skins['_skinr_id'];
      $skins = array('_skinr' =>  $_skinr, '_skinr_id' => $_skinr_id);
    }
    else{
      $skins = array_merge($skins, $exported_skins[$sid]->skins);       
    }
  }
 }
}

/**
 * Implementation of hook_form_alter().
 *
 * Skinr implements a pretty good set of hook functions, sadly the loading of skinr objects (skinr_get) 
 * are direct sql queries. So we'll need to merge the edit forms with the data from the exportable
 * at least while it's in a default state. When is overwritten we don't need to worry since it's change.
 * I might find a better way to do this down the road. Still new to skinr :) 
 */
function skinr_export_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'skinr_ui_form') {
    $exported_skins = _skinr_export_skins_load_only_code();
    if($exported_skins[$form['skinr']['sid']['#value']]){
      foreach ($exported_skins as $skin) {
        foreach($skin->skins as $skin_key => $skin_setting) {
          if ($skin_key != '_additional') {
            $form['skinr_settings']['block_group'][$skin->theme]['widgets'][$skin_key]['#default_value'] = $skin_setting;          
          }
          else {
            $form['skinr_settings']['block_group'][$skin->theme][$skin_key]['#default_value'] = $skin_setting;
          }
        }
      }
    }
  }  
}