<?php
// $Id$

/**
 * Implementation of hook_help().
 */
function skinr_export_help($path, $arg) {

}

/**
 * Implementation of hook_schema_alter().
 * Makes the skinr table usable by ctools' export.inc.
 */
function skinr_export_schema_alter(&$schema) {
  $schema['skinr']['export'] = array(
    'key' => 'sid',
    'primary key' => array('theme', 'module', 'sid'),
    'identifier' => 'skins',
    'default hook' => 'default_skinr_skins',
    'api' => array(
      'owner' => 'skinr',
      'api' => 'skinr',
      'minimum_version' => 1,
      'current_version' => 1,
    ), 
  );
}

/**
* Implementation of hook_ctools_plugin_api().
*/
function skinr_export_ctools_plugin_api($owner, $api) {
  if ($owner == 'skinr' && $api == 'skinr_skins') {
    return array('version' => 1);
  }
}

/**
 * Load a single skins object.
 */
function skinr_export_skins_load($name) {
  ctools_include('export');
  $result = ctools_export_load_object('skinr', 'names', array('sid' => $name));
  if (isset($result[$name])) {
    return $result[$name];
  }
}

/**
 * Load all skins object.
 */
function skinr_export_skins_load_all() {
  ctools_include('export');
  $result = ctools_export_load_object('skinr');
  return $result;
}

/**
 * Implementation of hook_skinr_alter().
 */
function skinr_export_skinr_skins_alter(&$skins, $module, $sids, $settings) {
 static $exported_skins;

 if (!isset($exported_skins)) {
  $exported_skins = skinr_export_skins_load_all();
 }

 foreach ($sids as $sid) {
  if (isset($exported_skins[$sid])) {
    $skins = $exported_skins[$sid]->skins;
  }
 }
}
